######################################################################
# Automatically generated by qmake (2.01a) ? 5? 30 15:11:15 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += editor.h
SOURCES += editor.cpp main.cpp slots.cpp
