######################################################################
# Automatically generated by qmake (2.01a) ? 9? 28 22:52:06 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += editor.h
SOURCES += editor.cpp main.cpp slots.cpp
